
package ch.uzh.winf.stockservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "StockService", targetNamespace = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface StockService {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getQuantityInStock", targetNamespace = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/", className = "ch.uzh.ifi.imrg.wi.sparctron.stockservice.GetQuantityInStock")
    @ResponseWrapper(localName = "getQuantityInStockResponse", targetNamespace = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/", className = "ch.uzh.ifi.imrg.wi.sparctron.stockservice.GetQuantityInStockResponse")
    @Action(input = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/StockService/getQuantityInStockRequest", output = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/StockService/getQuantityInStockResponse")
    public int getQuantityInStock(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponentNameById", targetNamespace = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/", className = "ch.uzh.ifi.imrg.wi.sparctron.stockservice.GetComponentNameById")
    @ResponseWrapper(localName = "getComponentNameByIdResponse", targetNamespace = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/", className = "ch.uzh.ifi.imrg.wi.sparctron.stockservice.GetComponentNameByIdResponse")
    @Action(input = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/StockService/getComponentNameByIdRequest", output = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/StockService/getComponentNameByIdResponse")
    public String getComponentNameById(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getComponentIdByName", targetNamespace = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/", className = "ch.uzh.ifi.imrg.wi.sparctron.stockservice.GetComponentIdByName")
    @ResponseWrapper(localName = "getComponentIdByNameResponse", targetNamespace = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/", className = "ch.uzh.ifi.imrg.wi.sparctron.stockservice.GetComponentIdByNameResponse")
    @Action(input = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/StockService/getComponentIdByNameRequest", output = "http://stockservice.sparctron.wi.imrg.ifi.uzh.ch/StockService/getComponentIdByNameResponse")
    public int getComponentIdByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
